import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { TimelineProvider } from "@/providers/TimelineProvider";
import { DebugProvider } from "@/providers/DebugProvider";
import { SmoothScrollProvider } from "@/providers/SmoothScrollProvider";
import { UniversalScrollLogger } from "@/components/UniversalScrollLogger";
// import { DebugPanel } from "@/components/DebugPanel";
import { Inter } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



const inter = Inter({ 
  subsets: ["latin"],
  variable: "--font-inter",
});

// Use inter.variable in your HTML className

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SmoothScrollProvider>
          <DebugProvider>
            <UniversalScrollLogger />
            <TimelineProvider>{children}</TimelineProvider>
            {/* <DebugPanel /> */}
          </DebugProvider>
        </SmoothScrollProvider>
      </body>
    </html>
  );
}
